### PR TITLE
Add support for OpenBSD ARM and RISC-V detection

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by animetosho** [comment]
Thanks!

I don't have a setup to test it, so I assume it's all the same as FreeBSD.

**Comment by brad0** [comment]
> Thanks!
> 
> I don't have a setup to test it, so I assume it's all the same as FreeBSD.

Yes, same API copied from FreeBSD.

**Comment by brad0** [comment]
@animetosho  Also this started as a patch for sabctools with the embedded copy of rapidyenc, but I'm pushing it all the way upstream so it can sync back the other direction.

**Comment by animetosho** [comment]
I see.

I'm a bit slow to push out releases and such, but if it helps, I've [updated rapidyenc](https://github.com/animetosho/rapidyenc/commit/47f67f5ae31455a4e7bb2566fb2b6c3c1b0105e9), which can be imported across to sabctools.

**Pull request merged**
